service: poc-poke
app: poc-poke
org: andrebariani

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: sa-east-1

functions:
  generateCode:
    handler: handler.handler
    events:
      - http:
          path: /api
          method: post
          cors: true

package:
  exclude:
    - tests/**