# This is a basic workflow to help you get started with Actions
# Miau
name: Build & Deploy

# inputs:
#   ExecuteDeploy:
#     description: 'Choice to deploy'
#     default: false

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'package.json'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'package.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_ACTION }}

    - name: CD to frontend
      run: cd frontend

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      
    - name: Build
      run: npm run ng -- build
      if: ${{github.event_name == 'push'}}  

    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v2
      with:
         github-token: ${{ secrets.TOKEN_ACTION }}
         output-file: 'false'
         git-message: 'bump: {version}'
      if: ${{github.event_name == 'push'}}  

    - name: ls
      run: echo steps.changelog.outputs.version
      if: ${{github.event_name == 'push'}}  

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
          name: 'pokemon-drag-drop'
          path: dist/
      if: ${{github.event_name == 'push'}}

    - name: Deploy Artifact
      uses: serverless/github-action@master
      with:
        args: client deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      if: ${{github.event_name == 'push' && env.INPUT_EXECUTEDEPLOY}}
