name: CD

on:
  pull_request_review:
    types: [submitted]
    paths-ignore:
      - 'package.json'

jobs:
  Build:
    if: contains(github.event.review.state, "approved")
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_ACTION }}

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Install dependencies
      run: npm ci

    # - name: Conventional Changelog Action
    #   id: changelog
    #   uses: TriPSs/conventional-changelog-action@v2
    #   with:
    #      github-token: ${{ secrets.TOKEN_ACTION }}
    #      output-file: 'false'
    #      git-message: 'bump: {version}'

    - name: Build
      run: npm run ng -- build

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
          name: 'pokemon-drag-drop'
          path: frontend/dist/

  Deploy:
    needs: Build
    if: contains(github.event.pull_request.labels.*.name, 'deploy')
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_ACTION }}

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: List last commits
      run: git log -n2

    - uses: actions/download-artifact@v2
      with:
        name: 'pokemon-drag-drop'
        path: frontend/dist/

    - name: Display structure of files
      run: ls -R

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.ADMIN_AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.ADMIN_AWS_SECRET_ACCESS_KEY }}
    #     aws-region: sa-east-1
        
    # - name: Deploy
    #   run: |
    #     aws s3 rm s3://poc-app-poke/ --recursive &&
    #     aws s3 cp dist/ProtoDnD/ s3://poc-app-poke/ --recursive