name: CD

on:
  push:
    branches: [ release ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_ACTION }}

    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run ng -- build --prod

    - name: Display structure of files
      run: ls -R

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ADMIN_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ADMIN_AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1
        
    - name: Deploy
      run: |
        aws s3 rm s3://poc-app-poke/ --recursive &&
        aws s3 cp dist/ProtoDnD/ s3://poc-app-poke/ --recursive