name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - './frontend/package.json'
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_ACTION }}

    - name: Install dependencies
      run: npm ci

    # - name: Run tests
    #   run: npm test
      
    - name: Build
      run: npm run ng -- build
      if: ${{github.event_name == 'push'}}

    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v2
      with:
         github-token: ${{ secrets.TOKEN_ACTION }}
         output-file: 'false'
         git-message: 'bump: {version}'
      if: ${{github.event_name == 'push'}}

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
          name: 'pokemon-drag-drop'
          path: frontend/dist/
      if: ${{github.event_name == 'push'}}