# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'package.json'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'package.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_ACTION }}

    - name: CD to frontend
      run: cd frontend

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      
    - name: Build
      run: npm run ng -- build
      if: ${{github.event_name == 'push'}}  

    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v2
      with:
         github-token: ${{ secrets.TOKEN_ACTION }}
         output-file: 'false'
         git-message: 'bump: {version}'
      if: ${{github.event_name == 'push'}}  

    - name: ls
      run: echo steps.changelog.outputs.version
      if: ${{github.event_name == 'push'}}  

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
          name: 'pokemon-drag-drop'
          path: dist/
      if: ${{github.event_name == 'push'}}

    - name: ls
      run: ls

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ADMIN_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ADMIN_AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: List Buckets
      run: aws s3 ls